BASEDIR=$(dirname "$0")

XCODE_VERSION="12_4"

OPT_CLANG_PATH=$BASEDIR/LLVM_tools/XCODE_${XCODE_VERSION}/bin/clang
OPT_CLANG_PP=$BASEDIR/LLVM_tools/XCODE_${XCODE_VERSION}//bin/clang++

export OPT_CLANG=$OPT_CLANG_PATH
export OPT_CLANG_PP=$OPT_CLANG_PP