# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JardinDeJuegos' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  use_modular_headers!

  pod 'Swinject'
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'JardinDeJuegosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JardinDeJuegosUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|

      opt_clang=ENV['OPT_CLANG']
      opt_clang_pp=ENV['OPT_CLANG_PP']

      if !(opt_clang.nil? || opt_clang.empty?)
       config.build_settings['CC'] = opt_clang
      end

      if !(opt_clang_pp.nil? || opt_clang_pp.empty?)
       config.build_settings['CXX'] = opt_clang_pp
      end

      if config.name == 'Release'
        config.build_settings['GCC_GENERATE_DEBUGGING_SYMBOLS'] = 'NO'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Osize'
        config.build_settings['GCC_OPTIMIZATION_LEVEL'] = 'z'
       config.build_settings['LLVM_LTO'] = 'YES'
        config.build_settings['ENABLE_BITCODE'] = 'YES'
      end
    end
  end
end
